"""empty message

Revision ID: 282fc8596c15
Revises: c4db4ecac346
Create Date: 2023-03-16 11:37:40.129643

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '282fc8596c15'
down_revision = 'c4db4ecac346'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tag',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=32), server_default='', nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['email'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    op.drop_table('tag')
    # ### end Alembic commands ###
